### ISSUE TITLE
[Meta] Add to Repo?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/script.skinvariables#1]
Do you want this added to the repo? Or hold off? Either way is fine, but I wasn't expecting *more* add-ons out of you 😅

**Comment by jurialmunkey** [comment]
@drinfernoo - Its the variables generator part of TMDbHelper. I decided to split it out into its own add-on so that skinners can use it without needing to have TMDbHelper installed.

End users don't actually need to have it installed to use the skin. It's just used on the skinners end to construct the variables and then the skinner can commit/push the includes file that it generates.

So, probably no need to bother adding it to the repo.

**Comment by drinfernoo** [comment]
Ah, very cool. I was imagining it being a runtime dependency of the skin. No worries 👍
