### ISSUE TITLE
Skin variables won't build unless forced.

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/script.skinvariables#11]
Skin variables won't build when using:-

`<onload>RunScript(script.skinvariables)</onload>`

They will build if I use:-

`<onload>RunScript(script.skinvariables,force)</onload>`

However using force causes my skin to go into an infinite reload cycle.

**Comment by jurialmunkey** [comment]
Why do you need to do this on load? You shouldnt build variables on the user side. Just build your variables when you change them and include the file it outputs in the skin.

There's no need to have skin variables as dependency unless you're specifically using other features (eg viewtype)

**Comment by roidy** [comment]
Because when you are initially developing your skin and making regular changes and additions to the variable template xml it would be nice to have the include generated automatically after any change to the definition xml. 

At the moment I'm having to comment and uncomment the runscript line and faff around as my skin goes into an infinite reload loop. 

I completely understand that once the include file is finalised then the script is not needed and I can just ship the generated include. But during development it's a pain :(

The Wiki states "The script will only build the variables if the template has changed.", I can only get it to build if I use "force" no matter how many changes I make to the template xml.

It seems this issue has come up before:- https://github.com/jurialmunkey/script.skinvariables/issues/2

You posted in that issue:-

```
It can still be useful to have it as an onload just so you don't need to run it manually when you make changes.
<onload condition="System.HasAddon(script.skinvariables)">Runscript(script.skinvariables)</onload>
That will make sure it only runs if you have it installed (so it won't prompt users if they don't have it installed).
```

**Comment by jurialmunkey** [comment]
Just realised you're running it bare without any params.

I forgot to document that you need to add a param of some sort and can't just run it bare anymore. I did that to stop people accidentally overwriting their setup by clicking on the script via MyPrograms (which was really annoying if you manually edited the output file after generating it, or if you didn't want to ship the source file in shortcuts).

Any param that isn't used for something else will work (that's why force works, and same if you specified folder=1080i etc.). However, I recommend using something clear like:
```
runscript(script.skinvariables,action=buildvariables)
```

**Comment by roidy** [comment]
Perfect, thank you 👍
