### ISSUE TITLE
buildviews dialogbusy

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/script.skinvariables#4]
Thanks for another great feature!

I have implemented the buildviews / view switching and everything appears to be working perfectly.

One issue I have noticed is that when script.skinvariables,action=buildviews is run on Home load, Dialogbusy is triggered which results in a "screen flash".

Is there anything script side you can do to prevent the dialogbusy triggering?

Thanks!

**Comment by jurialmunkey** [comment]
Maybe I should switch to DialogExtendedProgressBar instead - I forgot about fullscreen busy loaders.

**Comment by drinfernoo** [comment]
On the topic, @jurialmunkey... what are the different busy dialogs? I've seen a couple mentioned between add-ons that support both Kodi 17.x and 18.x, but am not sure which is the "right" one anymore.

Also, I've seen somewhere in TMDbHelper that there's a context manager busy dialog you've implemented. Could that type of approach be used for other custom windows?

**Comment by jurialmunkey** [comment]
@drinfernoo - 

**DialogBusy.xml**
This is the standard busy "spinner" shown in the top left in AH.

Opened with `ActivateWindow(busydialognocancel)` and closed with `Dialog.Close(busydialognocancel)`. 

I wrap these commands in function using the [context manager](https://book.pythontips.com/en/latest/context_managers.html) python decorator so that the closing of the dialog can be managed automatically using a `with:` statement. You can use a context manager for any code where you have a pair of related operations that you'd like to run a block of code between.

**DialogExtendedProgressBar.xml** 
This is the background progress dialog shown in the top right of AH. It is used by SkinShortcuts and UpdateLibrary (among others) to show progress without stealing focus.

It is controlled via the  `xbmcgui.DialogProgress()` class:
https://codedocs.xyz/AlwinEsch/kodi/group__python___dialog_progress_b_g.html

**DialogConfirm.xml (previously called DialogProgress.xml)**
This is the foreground progress dialog shown center screen in AH with a Cancel button. It is the same dialog as the yes/no and ok dialogs but with a progress bar. It steals focus and can be seen when you authenticate Trakt with an access code.

It is controlled via the `xbmcgui.DialogProgress()` class:
https://codedocs.xyz/AlwinEsch/kodi/group__python___dialog_progress.html

Really I should be using the BG progress dialog here since it is a background task. Dialog Busy should only really be used if the user has to wait for something to complete before doing anything else.

**Comment by drinfernoo** [comment]
It isn't possible to open other custom windows in the "background", is it?

**Comment by jurialmunkey** [comment]
@drinfernoo - If by custom window, you mean a custom skin xml window, yes you can. Have a look at Custom_Overlay.xml - that doesn't steal focus and you could send it to the background by altering the zorder so that it is lower than all the other windows
https://kodi.wiki/view/Skinning_Manual#Window_Header

**Comment by jurialmunkey** [comment]
@drinfernoo - Also see this forum thread for some ideas about doing this sort of thing from python:
https://forum.kodi.tv/showthread.php?tid=212811

**Comment by jurialmunkey** [comment]
@drinfernoo - If you want a python specific solution, you can just add the controls directly to the current window
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__window.html#ga0ebba3199e81c1400e1b75faeb8e9c91

**Comment by drinfernoo** [comment]
I've made a window positioned offscreen, but it definitely still steals focus, though I am calling it with `doModal()`... because it has work that needs to be done before the calling method can continue.

Unfortunately, this control I need to access is a `list` control, populated via a `<content>` tag, so that it can have dynamic content. As far as I can tell, there is no way to do this with a Python `ControlList`, unless *I* create the items to populate it with beforehand.

**Comment by skyfsza** [comment]
> Maybe I should switch to DialogExtendedProgressBar instead - I forgot about fullscreen busy loaders.
> 
> Also, great you got this working without any docs! I've really got to document it's usage (though I think it is probably pretty straight forward).

Latest update fixed the issue, thanks!

**Comment by skyfsza** [comment]
@jurialmunkey  Not sure if its related to this change, but I appear to be getting skin reloads after selecting a different view in the dialog.

`2020-05-30 13:49:31.190 T:9853   DEBUG: ------ Window Init (DialogSelect.xml) ------
2020-05-30 13:49:31.190 T:9853    INFO: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2020-05-30 13:49:34.026 T:9853   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
2020-05-30 13:49:34.202 T:9853   DEBUG: ------ Window Deinit (DialogSelect.xml) ------
2020-05-30 13:49:34.226 T:9853   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
2020-05-30 13:49:34.236 T:20791    INFO: CPythonInvoker(1186, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skinvariables/script.py): script successfully run
2020-05-30 13:49:34.236 T:20791   DEBUG: onExecutionDone(1186, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skinvariables/script.py)
2020-05-30 13:49:34.243 T:20792   DEBUG: Thread Timer start, auto delete: false
2020-05-30 13:49:34.247 T:9853    INFO: Unloading old skin ...
2020-05-30 13:49:34.280 T:9853   DEBUG: ------ Window Deinit () ------
2020-05-30 13:49:34.280 T:9853   DEBUG: ------ Window Deinit (MyVideoNav.xml) ------
2020-05-30 13:49:34.302 T:9853   DEBUG: ------ Window Deinit (Custom_Overlay.xml) ------
2020-05-30 13:49:34.306 T:9853   DEBUG: ------ Window Deinit (DialogExtendedProgressBar.xml) ------`

**Comment by jurialmunkey** [comment]
> Thinking about it some more, I assume the reload is needed so the script-skinviewtypes-includes.xml can be reloaded?

Yep. It's because the file needs to reload. I'm trying to come up with a different way of handling this so it doesn't need to reload.

Currently the script adds/removes the conditions from each expression. I was thinking it might be possible instead to have all the possible conditions in every expression but also add a skin string to each that tells whether it is enabled.

As a simple example, currently if Container.Content(movies) is set to the library for view ID 50, then the script adds `[Container.Content(movies) + String.IsEmpty(Container.PluginName)]` to the Exp_View_50 expression and removes it from the others.

It maybe possible instead to have something like `[Container.Content(movies) + String.IsEmpty(Container.PluginName) + Skin.String(SkinViewtypes.Movies,ID50)]` in each view - where ID50 is the value for that particular view. Then the script would update the skin string to change views, so it wouldn't be necessary for a reload. I'm just trying to figure out how to deal with the conditions for individual plugins...

**Comment by skyfsza** [comment]
> > Thinking about it some more, I assume the reload is needed so the script-skinviewtypes-includes.xml can be reloaded?
> 
> Yep. It's because the file needs to reload. I'm trying to come up with a different way of handling this so it doesn't need to reload.
> 
I dont think its a huge problem doing the reloads as I would expect users set the views once and then rarely change, but obviously would be better without.

> Currently the script adds/removes the conditions from each expression. I was thinking it might be possible instead to have all the possible conditions in every expression but also add a skin string to each that tells whether it is enabled.
> 
> As a simple example, currently if Container.Content(movies) is set to the library for view ID 50, then the script adds `[Container.Content(movies) + String.IsEmpty(Container.PluginName)]` to the Exp_View_50 expression and removes it from the others.
> 
> It maybe possible instead to have something like `[Container.Content(movies) + String.IsEmpty(Container.PluginName) + Skin.String(SkinViewtypes.Movies,ID50)]` in each view - where ID50 is the value for that particular view. Then the script would update the skin string to change views, so it wouldn't be necessary for a reload. I'm just trying to figure out how to deal with the conditions for individual plugins...

This sounds like a good idea for Content based conditions, how would this work for addons/plugins? eg:

`[Container.Content(movies) + [String.IsEqual(Container.PluginName,plugin.video.themoviedb.helper) `

**Comment by jurialmunkey** [comment]
> I dont think its a huge problem doing the reloads as I would expect users set the views once and then rarely change, but obviously would be better without.

Yeah that's what I thought initially. I think most users don't compulsively mess around with settings as much as I do...

> This sounds like a good idea for Content based conditions, how would this work for addons/plugins? 

Yeah that's the major roadblock. I haven't been able to come up with a way around that yet -- at least not without having a fixed number of permitted addon customisations, which is not something that I want to do.
